import * as fs from "node:fs";
import * as path from "node:path";
import type Database from "better-sqlite3";

/**
 * Ensures the .pi-recall/ directory exists with subdirectories.
 */
export function ensurePiMemoryDir(cwd: string): string {
	const dir = path.join(cwd, ".pi-recall");
	fs.mkdirSync(dir, { recursive: true });
	fs.mkdirSync(path.join(dir, "mental-models"), { recursive: true });
	fs.mkdirSync(path.join(dir, "solutions"), { recursive: true });
	return dir;
}

/**
 * Generate/update PI_MEMORY.md at the project root.
 * Reads current state from DB to create a compact summary.
 */
export function generatePIMemoryMd(db: Database.Database, cwd: string): void {
	const now = new Date().toISOString().split("T")[0];
	const projectName = path.basename(cwd);

	// Count solutions by type
	const bugCount = (db.prepare(`SELECT COUNT(*) as c FROM solutions WHERE problem_type = 'bug'`).get() as { c: number }).c;
	const knowledgeCount = (db.prepare(`SELECT COUNT(*) as c FROM solutions WHERE problem_type = 'knowledge'`).get() as { c: number }).c;
	const decisionCount = (db.prepare(`SELECT COUNT(*) as c FROM solutions WHERE problem_type = 'decision'`).get() as { c: number }).c;

	// Recent solutions
	const recentSolutions = db.prepare(
		`SELECT title, problem_type, severity FROM solutions ORDER BY updated_at DESC LIMIT 5`,
	).all() as Array<{ title: string; problem_type: string; severity: string | null }>;

	// Recent decisions
	const recentDecisions = db.prepare(
		`SELECT title, content FROM solutions WHERE problem_type = 'decision' ORDER BY updated_at DESC LIMIT 3`,
	).all() as Array<{ title: string; content: string }>;

	// Read architecture/conventions if they exist
	let architectureSection = "_Not yet documented._";
	let conventionsSection = "_Not yet documented._";

	const archPath = path.join(cwd, ".pi-recall", "architecture.md");
	if (fs.existsSync(archPath)) {
		const content = fs.readFileSync(archPath, "utf-8");
		architectureSection = content.slice(0, 500);
	}

	const convPath = path.join(cwd, ".pi-recall", "conventions.md");
	if (fs.existsSync(convPath)) {
		const content = fs.readFileSync(convPath, "utf-8");
		conventionsSection = content.slice(0, 500);
	}

	// Active patterns
	let activePatterns = "";
	if (recentSolutions.length > 0) {
		activePatterns = recentSolutions
			.map((s) => `- ${s.title} (${s.problem_type}${s.severity ? `, ${s.severity}` : ""})`)
			.join("\n");
	} else {
		activePatterns = "_No solutions recorded yet._";
	}

	// Recent decisions
	let decisionsSection = "";
	if (recentDecisions.length > 0) {
		decisionsSection = recentDecisions
			.map((d) => `- **${d.title}**: ${d.content.slice(0, 200)}`)
			.join("\n");
	} else {
		decisionsSection = "_No decisions recorded yet._";
	}

	const content = `# Project Memory: ${projectName}
> Auto-generated by pi-recall. Updated: ${now}

## Architecture
${architectureSection}

## Conventions
${conventionsSection}

## Active Patterns
${activePatterns}

## Recent Decisions
${decisionsSection}

## Stats
- Bug solutions: ${bugCount}
- Knowledge patterns: ${knowledgeCount}
- Decisions: ${decisionCount}
`;

	fs.writeFileSync(path.join(cwd, "PI_MEMORY.md"), content, "utf-8");
}

/**
 * Update a markdown file in .pi-recall/ (append section or overwrite).
 */
export function updateMarkdownFile(
	cwd: string,
	name: string,
	content: string,
): void {
	const filePath = path.join(cwd, ".pi-recall", `${name}.md`);
	ensurePiMemoryDir(cwd);
	fs.writeFileSync(filePath, content, "utf-8");
}

/**
 * Read a markdown file from .pi-recall/.
 */
export function readMarkdownFile(cwd: string, name: string): string | null {
	const filePath = path.join(cwd, ".pi-recall", `${name}.md`);
	try {
		return fs.readFileSync(filePath, "utf-8");
	} catch {
		return null;
	}
}
