import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import BetterSqlite3 from "better-sqlite3";
import type Database from "better-sqlite3";
import { initSchema } from "../../src/store/schema.ts";
import {
	ensurePiMemoryDir,
	generatePIMemoryMd,
	updateMarkdownFile,
	readMarkdownFile,
} from "../../src/memory/hierarchical.ts";

function createTestDB(): { db: Database.Database; dir: string; cleanup: () => void } {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	const db = new BetterSqlite3(path.join(dir, "test.db")) as unknown as Database.Database;
	initSchema(db);
	return {
		db,
		dir,
		cleanup: () => {
			db.close();
			fs.rmSync(dir, { recursive: true, force: true });
		},
	};
}

test("ensurePiMemoryDir creates directory structure", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	try {
		const result = ensurePiMemoryDir(dir);
		assert.ok(fs.existsSync(path.join(dir, ".pi-memory")));
		assert.ok(fs.existsSync(path.join(dir, ".pi-memory", "mental-models")));
		assert.ok(fs.existsSync(path.join(dir, ".pi-memory", "solutions")));
		assert.equal(result, path.join(dir, ".pi-memory"));
	} finally {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("ensurePiMemoryDir is idempotent", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	try {
		ensurePiMemoryDir(dir);
		assert.doesNotThrow(() => ensurePiMemoryDir(dir));
	} finally {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("generatePIMemoryMd creates PI_MEMORY.md", () => {
	const { db, dir, cleanup } = createTestDB();
	try {
		generatePIMemoryMd(db, dir);
		const mdPath = path.join(dir, "PI_MEMORY.md");
		assert.ok(fs.existsSync(mdPath));

		const content = fs.readFileSync(mdPath, "utf-8");
		assert.ok(content.includes("Project Memory:"));
		assert.ok(content.includes("Auto-generated by pi-recall"));
		assert.ok(content.includes("## Stats"));
	} finally {
		cleanup();
	}
});

test("generatePIMemoryMd includes project name", () => {
	const { db, dir, cleanup } = createTestDB();
	try {
		generatePIMemoryMd(db, dir);
		const content = fs.readFileSync(path.join(dir, "PI_MEMORY.md"), "utf-8");
		const projectName = path.basename(dir);
		assert.ok(content.includes(projectName));
	} finally {
		cleanup();
	}
});

test("updateMarkdownFile creates file in .pi-memory", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	try {
		updateMarkdownFile(dir, "gotchas", "# Gotchas\n\n- Test gotcha");
		const content = fs.readFileSync(path.join(dir, ".pi-memory", "gotchas.md"), "utf-8");
		assert.ok(content.includes("Test gotcha"));
	} finally {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("updateMarkdownFile overwrites existing content", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	try {
		updateMarkdownFile(dir, "test", "Version 1");
		updateMarkdownFile(dir, "test", "Version 2");
		const content = fs.readFileSync(path.join(dir, ".pi-memory", "test.md"), "utf-8");
		assert.equal(content, "Version 2");
	} finally {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("readMarkdownFile returns null for non-existent", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	try {
		assert.equal(readMarkdownFile(dir, "nonexistent"), null);
	} finally {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("readMarkdownFile returns content for existing file", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-recall-hier-"));
	try {
		updateMarkdownFile(dir, "test", "Hello World");
		assert.equal(readMarkdownFile(dir, "test"), "Hello World");
	} finally {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});
